version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env  # Ensure the .env file is specified here
    volumes:
      - .:/app  # Mount the current directory to /app in the container