version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=your_database_url
      - FIREBASE_CREDENTIALS=cred.json
    volumes:
      - .:/app  # Mount the current directory to /app in the container